apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
  name: website-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: website
  type: NodePort